//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNinja.KubernetesModule.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetNinja.KubernetesModule.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMESPACE              NAME        HOSTS                      ADDRESS         PORTS   AGE
        ///istio-system           kiali       kiali.minikube.local       192.168.43.51   80      3d23h
        ///kubernetes-dashboard   dashboard   dashboard.minikube.local   192.168.43.51   80      3d23h.
        /// </summary>
        internal static string ExampleIngressData {
            get {
                return ResourceManager.GetString("ExampleIngressData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMESPACE              NAME        HOSTS                      ADDRESS         PORTS   AGE
        ///istio-system           kiali       kiali.minikube.local       192.168.43.51   80      3d23h
        ///kubernetes-dashboard   dashboard   dashboard.minikube.local   192.168.43.51   80.
        /// </summary>
        internal static string ExampleIngressDataWithInvalidRecord {
            get {
                return ResourceManager.GetString("ExampleIngressDataWithInvalidRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExampleIngressWithNonStandardPorts {
            get {
                return ResourceManager.GetString("ExampleIngressWithNonStandardPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMESPACE              NAME        HOSTS                      ADDRESS         PORTS   AGE
        ///istio-system           kiali       kiali.minikube.local       192.168.43.51   80      3d23h.
        /// </summary>
        internal static string ExampleIngressWithSingleRecord {
            get {
                return ResourceManager.GetString("ExampleIngressWithSingleRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Copyright (c) 1993-2009 Microsoft Corp.
        ///#
        ///# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
        ///#
        ///# This file contains the mappings of IP addresses to host names. Each
        ///# entry should be kept on an individual line. The IP address should
        ///# be placed in the first column followed by the corresponding host name.
        ///# The IP address and the host name should be separated by at least one
        ///# space.
        ///#
        ///# Additionally, comments (such as these) may be inserted on individual
        ///# lines or following th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleFileData {
            get {
                return ResourceManager.GetString("SampleFileData", resourceCulture);
            }
        }
    }
}
